/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class Manager_GUI extends javax.swing.JFrame {
    
    int btnClicked = 1;
    
    int mousepX;
    int mousepY;
    /**
     * Creates new form Admin_GUI
     */
    public Manager_GUI() {
        initComponents();
        
        TrangChu_GUI pnTrangChu = new TrangChu_GUI();
        showPanel(pnTrangChu);
        
        btnClicked();
        
        lbHoTenOnline.setText(DangNhap_GUI.hoTenOnline);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnQuanLyKH = new javax.swing.JButton();
        btnQuanLyNCC = new javax.swing.JButton();
        btnQuanLySP = new javax.swing.JButton();
        btnQuanLyDM = new javax.swing.JButton();
        btnQuanLyHD = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnTrangChu = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnQuanLyPhieuNhap = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        pnTitileBar = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        lbMinimize = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbHoTenOnline = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(0, 126, 167));
        setUndecorated(true);
        setResizable(false);

        pnMenu.setBackground(new java.awt.Color(0, 204, 204));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDangXuat.setBackground(new java.awt.Color(255, 204, 0));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-rounded-left-26.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(null);
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseExited(evt);
            }
        });
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnMenu.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 122, 35));

        btnQuanLyKH.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-groups-26.png"))); // NOI18N
        btnQuanLyKH.setText("Quản lý khách hàng");
        btnQuanLyKH.setBorder(null);
        btnQuanLyKH.setBorderPainted(false);
        btnQuanLyKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyKHMouseExited(evt);
            }
        });
        btnQuanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKHActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLyKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 255, 39));

        btnQuanLyNCC.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyNCC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-truck-26.png"))); // NOI18N
        btnQuanLyNCC.setText("Quản lý nhà cung cấp");
        btnQuanLyNCC.setBorder(null);
        btnQuanLyNCC.setBorderPainted(false);
        btnQuanLyNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNCC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyNCCMouseExited(evt);
            }
        });
        btnQuanLyNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNCCActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLyNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 255, 39));

        btnQuanLySP.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLySP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLySP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-26.png"))); // NOI18N
        btnQuanLySP.setText("Quản lý sản phẩm");
        btnQuanLySP.setBorder(null);
        btnQuanLySP.setBorderPainted(false);
        btnQuanLySP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLySP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLySPMouseExited(evt);
            }
        });
        btnQuanLySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySPActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLySP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 255, 39));

        btnQuanLyDM.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyDM.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-product-management-26.png"))); // NOI18N
        btnQuanLyDM.setText("Quản lý danh mục");
        btnQuanLyDM.setBorder(null);
        btnQuanLyDM.setBorderPainted(false);
        btnQuanLyDM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyDM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyDMMouseExited(evt);
            }
        });
        btnQuanLyDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDMActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLyDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 255, 39));

        btnQuanLyHD.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyHD.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-receipt-26.png"))); // NOI18N
        btnQuanLyHD.setText("Quản lý hóa đơn");
        btnQuanLyHD.setBorder(null);
        btnQuanLyHD.setBorderPainted(false);
        btnQuanLyHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyHDMouseExited(evt);
            }
        });
        btnQuanLyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHDActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLyHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 255, 39));

        btnThongKe.setBackground(new java.awt.Color(128, 216, 255));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-account-26.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setBorder(null);
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pnMenu.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 255, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-1.png"))); // NOI18N
        pnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        pnMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 275, 10));

        btnTrangChu.setBackground(new java.awt.Color(128, 216, 255));
        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-home-26.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setInheritsPopupMenu(true);
        btnTrangChu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        pnMenu.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 255, 39));

        btnBanHang.setBackground(new java.awt.Color(128, 216, 255));
        btnBanHang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-sell-27.png"))); // NOI18N
        btnBanHang.setText("Bán hàng");
        btnBanHang.setBorder(null);
        btnBanHang.setBorderPainted(false);
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanHangMouseExited(evt);
            }
        });
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        pnMenu.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 255, 39));

        btnQuanLyPhieuNhap.setBackground(new java.awt.Color(128, 216, 255));
        btnQuanLyPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLyPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-database-import-24.png"))); // NOI18N
        btnQuanLyPhieuNhap.setText("Quản lý phiếu nhập");
        btnQuanLyPhieuNhap.setBorder(null);
        btnQuanLyPhieuNhap.setBorderPainted(false);
        btnQuanLyPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyPhieuNhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyPhieuNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyPhieuNhapMouseExited(evt);
            }
        });
        btnQuanLyPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhieuNhapActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanLyPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 255, 39));

        pnTitileBar.setBackground(new java.awt.Color(102, 102, 102));
        pnTitileBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnTitileBar.setAlignmentX(0.0F);
        pnTitileBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnTitileBarMouseDragged(evt);
            }
        });
        pnTitileBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTitileBarMousePressed(evt);
            }
        });

        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-xbox-x-20.png"))); // NOI18N
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });

        lbMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-minimize-window-20.png"))); // NOI18N
        lbMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizeMouseClicked(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("SNEAKER STORE");
        lbTitle.setMaximumSize(new java.awt.Dimension(20, 20));
        lbTitle.setMinimumSize(new java.awt.Dimension(20, 20));
        lbTitle.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        lbHoTenOnline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHoTenOnline.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTenOnline.setText("name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manager -");

        javax.swing.GroupLayout pnTitileBarLayout = new javax.swing.GroupLayout(pnTitileBar);
        pnTitileBar.setLayout(pnTitileBarLayout);
        pnTitileBarLayout.setHorizontalGroup(
            pnTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitileBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHoTenOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(486, 486, 486)
                .addComponent(lbMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbExit)
                .addGap(18, 18, 18))
        );
        pnTitileBarLayout.setVerticalGroup(
            pnTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitileBarLayout.createSequentialGroup()
                .addGroup(pnTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbExit, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lbMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoTenOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE))
            .addComponent(pnTitileBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitileBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        DangNhap_GUI frmDangNhap = new DangNhap_GUI();
        
        frmDangNhap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQuanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKHActionPerformed
        QuanLyKhachHang_GUI pnQLKH = new QuanLyKhachHang_GUI();

        showPanel(pnQLKH);
    }//GEN-LAST:event_btnQuanLyKHActionPerformed

    private void btnQuanLyNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNCCActionPerformed
        QuanLyNCC_GUI pnQLNCC = new QuanLyNCC_GUI();

        showPanel(pnQLNCC);
    }//GEN-LAST:event_btnQuanLyNCCActionPerformed

    private void btnQuanLySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySPActionPerformed
        QuanLySanPham_GUI pnQLSP = new QuanLySanPham_GUI();

        showPanel(pnQLSP);
    }//GEN-LAST:event_btnQuanLySPActionPerformed

    private void btnQuanLyDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDMActionPerformed
        QuanLyDanhMuc_GUI pnQLDM = new QuanLyDanhMuc_GUI();

        showPanel(pnQLDM);
    }//GEN-LAST:event_btnQuanLyDMActionPerformed

    private void btnQuanLyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHDActionPerformed
        QuanLyHoaDon_GUI pnQLHD = new QuanLyHoaDon_GUI();

        showPanel(pnQLHD);
    }//GEN-LAST:event_btnQuanLyHDActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        ThongKe_GUI pnThongKe = new ThongKe_GUI();

        showPanel(pnThongKe);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        TrangChu_GUI pnTrangChu = new TrangChu_GUI();
        
        showPanel(pnTrangChu);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    //End show Panel
    
    
    //Start Hover button
    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered
        btnColorHover(btnTrangChu);
        //btnTrangChu.setBackground(new Color(0,255,153)); //hover Xanh lá
    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited
        if (btnClicked != 1){
            btnColorOrigin(btnTrangChu);
        }
    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnQuanLyKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseEntered
        btnColorHover(btnQuanLyKH);
    }//GEN-LAST:event_btnQuanLyKHMouseEntered

    private void btnQuanLyKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseExited
        if (btnClicked != 3){
            btnColorOrigin(btnQuanLyKH);
        }
    }//GEN-LAST:event_btnQuanLyKHMouseExited

    private void btnQuanLyNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseEntered
        btnColorHover(btnQuanLyNCC);
    }//GEN-LAST:event_btnQuanLyNCCMouseEntered

    private void btnQuanLyNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseExited
        if (btnClicked != 4){
            btnColorOrigin(btnQuanLyNCC);
        }
    }//GEN-LAST:event_btnQuanLyNCCMouseExited

    private void btnQuanLySPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseEntered
        btnColorHover(btnQuanLySP);
    }//GEN-LAST:event_btnQuanLySPMouseEntered

    private void btnQuanLySPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseExited
        if (btnClicked != 5){
            btnColorOrigin(btnQuanLySP);
        }
    }//GEN-LAST:event_btnQuanLySPMouseExited

    private void btnQuanLyDMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseEntered
        btnColorHover(btnQuanLyDM);
    }//GEN-LAST:event_btnQuanLyDMMouseEntered

    private void btnQuanLyDMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseExited
        if (btnClicked != 6){
            btnColorOrigin(btnQuanLyDM);
        }
    }//GEN-LAST:event_btnQuanLyDMMouseExited

    private void btnQuanLyHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseEntered
        btnColorHover(btnQuanLyHD);
    }//GEN-LAST:event_btnQuanLyHDMouseEntered

    private void btnQuanLyHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseExited
        if (btnClicked != 7){
            btnColorOrigin(btnQuanLyHD);
        }
    }//GEN-LAST:event_btnQuanLyHDMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        btnColorHover(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        if (btnClicked != 9){
            btnColorOrigin(btnThongKe);
        }   
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseEntered
        btnDangXuat.setBackground(new Color(255,204,102)); //Cam nhat
    }//GEN-LAST:event_btnDangXuatMouseEntered

    private void btnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseExited
        btnDangXuat.setBackground(new Color(255,204,0)); //Cam
    }//GEN-LAST:event_btnDangXuatMouseExited

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        btnClicked = 9;
        btnClicked();
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseClicked
        btnClicked = 1;
        btnClicked();
    }//GEN-LAST:event_btnTrangChuMouseClicked

    private void btnQuanLyKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyKHMouseClicked
        btnClicked = 3;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyKHMouseClicked

    private void btnQuanLyNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNCCMouseClicked
        btnClicked = 4;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyNCCMouseClicked

    private void btnQuanLySPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySPMouseClicked
        btnClicked = 5;
        btnClicked();
    }//GEN-LAST:event_btnQuanLySPMouseClicked

    private void btnQuanLyDMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyDMMouseClicked
        btnClicked = 6;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyDMMouseClicked

    private void btnQuanLyHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHDMouseClicked
        btnClicked = 7;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyHDMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
       btnClicked = 8;
        btnClicked();
    }//GEN-LAST:event_btnBanHangMouseClicked

    private void btnBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseExited
        if (btnClicked != 8){
            btnColorOrigin(btnBanHang);
        }
    }//GEN-LAST:event_btnBanHangMouseExited

    private void btnBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseEntered
        btnColorHover(btnBanHang);
    }//GEN-LAST:event_btnBanHangMouseEntered

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        BanHang_GUI pnBanHang = new BanHang_GUI();
        
        showPanel(pnBanHang);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizeMouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbMinimizeMouseClicked

    private void pnTitileBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTitileBarMouseDragged
        int toaDoX = evt.getXOnScreen();
        int toaDoY = evt.getYOnScreen();
        
        this.setLocation(toaDoX-mousepX, toaDoY-mousepY);
    }//GEN-LAST:event_pnTitileBarMouseDragged

    private void pnTitileBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTitileBarMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_pnTitileBarMousePressed

    private void btnQuanLyPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhieuNhapMouseClicked
        btnClicked = 10;
        btnClicked();
    }//GEN-LAST:event_btnQuanLyPhieuNhapMouseClicked

    private void btnQuanLyPhieuNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhieuNhapMouseEntered
       btnColorHover(btnQuanLyPhieuNhap);
    }//GEN-LAST:event_btnQuanLyPhieuNhapMouseEntered

    private void btnQuanLyPhieuNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhieuNhapMouseExited
        if (btnClicked != 10){
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
    }//GEN-LAST:event_btnQuanLyPhieuNhapMouseExited

    private void btnQuanLyPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhieuNhapActionPerformed
        QuanLyNhapHang_GUI pnQLNH = new QuanLyNhapHang_GUI();

        showPanel(pnQLNH);
    }//GEN-LAST:event_btnQuanLyPhieuNhapActionPerformed
    //End Hover button
    
    
    private void showPanel(JPanel panelName){       
        pnMain.removeAll();
        pnMain.add(panelName);
        pnMain.validate();
    }
    
    private void btnColorHover(JButton btnName){
        btnName.setBackground(new Color(0,255,153));//Xanh la
    }
    
    private void btnColorOrigin(JButton btnName){
        btnName.setBackground(new Color(128,216,255)); //Xanh duong
    }
    
    private void btnClicked(){
        if (btnClicked == 1){
            btnColorHover(btnTrangChu);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
//        if (btnClicked == 2){
//            btnColorHover(btnQuanLyNV);
//            
//            btnColorOrigin(btnTrangChu);
//            btnColorOrigin(btnQuanLyKH);
//            btnColorOrigin(btnQuanLyNCC);
//            btnColorOrigin(btnQuanLySP);
//            btnColorOrigin(btnQuanLyDM);
//            btnColorOrigin(btnQuanLyHD);
//            btnColorOrigin(btnBanHang);
//            btnColorOrigin(btnThongKe);
//        }
        
        if (btnClicked == 3){
            btnColorHover(btnQuanLyKH);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
        if (btnClicked == 4){
            btnColorHover(btnQuanLyNCC);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
        if (btnClicked == 5){
            btnColorHover(btnQuanLySP);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
        if (btnClicked == 6){
            btnColorHover(btnQuanLyDM);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
        if (btnClicked == 7){
            btnColorHover(btnQuanLyHD);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        
        if (btnClicked == 8){
            btnColorHover(btnBanHang);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnThongKe);
            btnColorOrigin(btnQuanLyPhieuNhap);
        }
        if (btnClicked == 9){
            btnColorHover(btnThongKe);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyPhieuNhap);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnTrangChu);
        }
        if (btnClicked == 10){
            btnColorHover(btnQuanLyPhieuNhap);
            
            //btnColorOrigin(btnQuanLyNV);
            btnColorOrigin(btnQuanLyKH);
            btnColorOrigin(btnQuanLyNCC);
            btnColorOrigin(btnQuanLySP);
            btnColorOrigin(btnQuanLyDM);
            btnColorOrigin(btnQuanLyHD);
            btnColorOrigin(btnBanHang);
            btnColorOrigin(btnTrangChu);
            btnColorOrigin(btnThongKe);
        }
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQuanLyDM;
    private javax.swing.JButton btnQuanLyHD;
    private javax.swing.JButton btnQuanLyKH;
    private javax.swing.JButton btnQuanLyNCC;
    private javax.swing.JButton btnQuanLyPhieuNhap;
    private javax.swing.JButton btnQuanLySP;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbHoTenOnline;
    private javax.swing.JLabel lbMinimize;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTitileBar;
    // End of variables declaration//GEN-END:variables
}
